/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asociaciones.pantallas;

/**
 *
 * @author Personal
 */
public class PantallaGestordeCursos extends javax.swing.JPanel {

    /**
     * Creates new form PantallaGestordeCursos
     */
    public PantallaGestordeCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarCurso = new javax.swing.JTextField();
        btnBuscarCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGestordeCursos = new javax.swing.JList<>();
        btnVerProfesoresCurso = new javax.swing.JButton();
        btnVerEstudiantesCurso = new javax.swing.JButton();
        btnAgregarCurso = new javax.swing.JButton();
        btnEliminarCurso = new javax.swing.JButton();

        jLabel1.setText("Gestor de Cursos");

        txtBuscarCurso.setText("jTextField1");

        btnBuscarCurso.setBackground(new java.awt.Color(51, 153, 0));
        btnBuscarCurso.setLabel("Buscar");

        listGestordeCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listGestordeCursos);

        btnVerProfesoresCurso.setBackground(new java.awt.Color(0, 153, 153));
        btnVerProfesoresCurso.setLabel("Profesores");
        btnVerProfesoresCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProfesoresCursoActionPerformed(evt);
            }
        });

        btnVerEstudiantesCurso.setBackground(new java.awt.Color(102, 204, 255));
        btnVerEstudiantesCurso.setLabel("Estudiantes");

        btnAgregarCurso.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCurso.setLabel("Agregar");
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        btnEliminarCurso.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarCurso.setLabel("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCurso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVerProfesoresCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerEstudiantesCurso)
                        .addGap(31, 31, 31)
                        .addComponent(btnAgregarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCurso)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCurso))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerProfesoresCurso)
                    .addComponent(btnVerEstudiantesCurso)
                    .addComponent(btnAgregarCurso)
                    .addComponent(btnEliminarCurso))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerProfesoresCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProfesoresCursoActionPerformed
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnVerProfesoresCursoActionPerformed

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JButton btnVerEstudiantesCurso;
    private javax.swing.JButton btnVerProfesoresCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listGestordeCursos;
    private javax.swing.JTextField txtBuscarCurso;
    // End of variables declaration//GEN-END:variables
}
